config/routes.rb
Rails.application.routes.draw do

  resources :items
  resources :recipes
  resources :quantities

end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :quantities
end

app/models/quantity.rb
class Quantity < ActiveRecord::Base
  belongs_to :item
  belongs_to :recipe

  accepts_nested_attributes_for :item
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :result, class_name: "Item"

  has_many :quantities
  has_many :items, through: :quantities

  accepts_nested_attributes_for :quantities

  def add_item(item_id, amount)
    added_item = quantities.find_by(item_id: item_id)
    if added_item
      added_item.amount += amount.to_i
    else
      added_item = quantities.build(item_id: item_id, amount: amount)
    end
    return added_item
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to items_path
  end

  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to items_path
    else
      render edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path
  end

  private
  def item_params
    params.require(:item).permit(:name, :url)
  end
end

app/controllers/quantities_controller.rb
class QuantitiesController < ApplicationController
  def destroy
    @quantity = Quantity.find(params[:id])
    return_id = @quantity.recipe_id
    @quantity.destroy
    redirect_to edit_recipe_path(id: return_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all
  end

  def new
    @items = Item.all
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.save
    redirect_to recipes_path
  end

  #Edit
  #Params:
  #   (str)  id
  #   (str)  extrablank
  #
  #should lookup a recipe and add an amount of blank entries equal to @extrablank
  def edit
    params[:extrablank].nil? ? @extrablank = 1 : @extrablank = params[:extrablank].to_i
    @items = Item.all
    @recipe = Recipe.find(params[:id])
    @extrablank.times do
      @recipe.quantities.build
    end
    #    @ingredients ? @ingredients << Item.new : @ingredients = [Item.new]
  end

  #Update
  #Params:
  #   (str)  id
  #   (hash) recipe
  #     (str)  result_id
  #     (hash) quantities_attributes
  #       (hash) <attr index>
  #         (str)  result_id
  #         (str)  amount
  #         (str)  item_id
  #
  #Should update a recipe of given ID
  #Should not update a quantity if the amount or item id is null
  #
  def update
    @recipe = Recipe.find(params[:id])
    db_quantities = @recipe.quantities.where("recipe_id = :this_id", {this_id: @recipe.id})

    params[:recipe][:quantities_attributes].each do |quantity_raw|
      quantity = quantity_raw.to_a.last
      if quantity[:item_id].blank?
        next
      end
      #Look to see if the item name is already there and if it is, replace the new amount
      if db_quantities.map{|q| q.item_id}.include?(quantity[:item_id].to_i)
        (db_quantities.detect{|q| q.item_id == quantity[:item_id].to_i})
          .update(amount: quantity[:amount].to_i)
      else
        @recipe.add_item(quantity[:item_id], quantity[:amount])
      end

    end

    @recipe.attributes = recipe_params
    if @recipe.update_attributes(recipe_params)
      redirect_to edit_recipe_url, id: @recipe.id
    else
      render edit
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path
  end

  private
  def recipe_params
    params.require(:recipe).permit(
      :result_id,
      :quantities => [
        :id,
        :amount,
        :item_id,
      ])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/items/edit.html.erb
<h1>Edit item <%= @item.name %></h1>

<%= form_for(@item) do |f| %>
  <div class="field">
    <%= f.label :name %>:<br>
    <%= f.text_field :name %>
  </div>
  <br>
  <div>
    <%= f.label :url %>:<br>
    <%= f.text_field :url %>
  </div>
  <br>
  <div class="form_sumbit">
    <%= f.submit %>
  </div>
<% end %>
<br><br>
<%= link_to "Back", items_path %>

app/views/items/index.html.erb
<h1>Items</h1>

<br>

<table>
  <tr>
    <th>Name</th>
  </tr>
  <% @items.each do |item| %>
    <tr>
      <td><%= link_to item.name, item.url %></td>
      <td><%= link_to :edit, edit_item_path(item) %></td>
      <td><%= link_to :delete, item_path(item), method: :delete,
                               data: { confirm: "Delete #{item[:name]}?" } %></td>
    </tr>
  <% end %>
</table>

<br><br>

<%= link_to :New, new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= form_for(@item) do |f| %>
  <div class="field">
    <%= f.label :name %>:<br>
    <%= f.text_field :name %>
  </div>
  <br>
  <div>
    <%= f.label :url %>:<br>
    <%= f.text_field :url %>
  </div>
  <br>
  <div class="form_sumbit">
    <%= f.submit %>
  </div>
<% end %>
<br><br>
<%= link_to "Back", items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gatherer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recipes/edit.html.erb
<h1>Edit recipe <%= @recipe.id %></h1>

<%= form_for(@recipe) do |f| %>
  <div class="field">
    <%= f.label :Result %>:<br>
    <%= f.collection_select :result_id, @items, :id, :name %>
  </div>
  <br>
  <div class="items">
    <%= f.fields_for :quantities do |ff| %>
      <div class="item_fields">
        <%= ff.hidden_field :id %>
        <%= ff.text_field :amount %>
        <% unless ff.object.item_id %>
          <%= ff.collection_select :item_id, @items, :id, :name, prompt: true%>
          <%= f.submit "Add" %><br>
        <% else %>
          <%= (@items.detect{|i| i.id == ff.object.item_id}).name %>
          <%= link_to "Delete", quantity_path(id: ff.object.id), method: :delete %>
          <%= ff.hidden_field :item_id %>
        <% end %>
      </div>
    <% end %>
  <div class="form_sumbit">
    <%= f.submit %>
  </div>
<% end %>
<br><br>
<%= link_to "Back", recipes_path %>

app/views/recipes/index.html.erb
<h1>Recipes</h1>

<br>

<table>
  <tr>
    <th>Name</th>
    <th>Created at</th>
    <th>Updated at</th>
    <th>Result</th>
  </tr>
  <% @recipes.each do |recipe| %>
    <tr>
      <td><%= recipe.id %></td>
      <td><%= recipe.created_at %></td>
      <td><%= recipe.updated_at %></td>
      <td><%= recipe.result ? recipe.result.name : "No result" %></td>
      <td><%= link_to :edit, edit_recipe_path(recipe) %></td>
      <td><%= link_to :delete, recipe_path(recipe), method: :delete,
                               data: { confirm: "Delete #{recipe[:name]}?" } %></td>
    </tr>
  <% end %>
</table>

<br><br>

<%= link_to :New, new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= form_for(@recipe) do |f| %>
  <div class="field">
    <%= f.label :Result %>:<br>
    <%= f.collection_select :result_id, @items, :id, :name %>
  </div>
  <br>
  <div class="form_sumbit">
    <%= f.submit %>
  </div>
<% end %>
<br><br>
<%= link_to "Back", recipes_path %>